"""empty message

Revision ID: 03915aad2eb5
Revises: a82ce668517a
Create Date: 2023-03-29 14:10:17.880881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03915aad2eb5'
down_revision = 'a82ce668517a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_planets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_peoples', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_peoples'], ['people.id'], name='favorites_id_peoples_fkey'),
    sa.ForeignKeyConstraint(['id_planets'], ['planet.id'], name='favorites_id_planets_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='favorites_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    # ### end Alembic commands ###
