"""empty message

Revision ID: 1fc94188baed
Revises: c2879679b984
Create Date: 2023-03-28 15:54:20.454223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc94188baed'
down_revision = 'c2879679b984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    with op.batch_alter_table('favorite__people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_people', sa.Integer(), nullable=False))
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('favorite__people_id_peoples_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['id_people'], ['id'])
        batch_op.drop_column('id_peoples')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite__people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_peoples', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite__people_id_peoples_fkey', 'people', ['id_peoples'], ['id'])
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('id_people')

    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_planets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_peoples', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_peoples'], ['people.id'], name='favorites_id_peoples_fkey'),
    sa.ForeignKeyConstraint(['id_planets'], ['planet.id'], name='favorites_id_planets_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='favorites_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    # ### end Alembic commands ###
