"""empty message

Revision ID: e2985415cf65
Revises: 095f07385c72
Create Date: 2023-03-29 11:19:02.105149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2985415cf65'
down_revision = '095f07385c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite__people', schema=None) as batch_op:
        batch_op.drop_constraint('favorite__people_name_key', type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite__people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('favorite__people_name_key', ['name'])

    # ### end Alembic commands ###
