"""empty message

Revision ID: e8632e66073f
Revises: d450a85cc8dc
Create Date: 2023-03-29 11:57:04.030687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8632e66073f'
down_revision = 'd450a85cc8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_planets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_peoples', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_peoples'], ['people.id'], name='favorites_id_peoples_fkey'),
    sa.ForeignKeyConstraint(['id_planets'], ['planet.id'], name='favorites_id_planets_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name='favorites_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    # ### end Alembic commands ###
